//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommanderProfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommanderProfiles()
        {
            this.Armies = new HashSet<Armies>();
        }
    
        public int Id { get; set; }
        public string CommanderName { get; set; }
        public int CommanderStrength { get; set; }
        public int CommanderResistance { get; set; }
        public int CommanderAttacks { get; set; }
        public int CommanderLives { get; set; }
        public Nullable<int> CommanderWeapon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Armies> Armies { get; set; }
        public virtual Weapons Weapons { get; set; }
    }
}
