//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsForArmies
    {
        public int Id { get; set; }
        public int UnitProfileID { get; set; }
        public int ArmyID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Armies Armies { get; set; }
        public virtual UnitProfiles UnitProfiles { get; set; }
    }
}
