//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitProfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnitProfiles()
        {
            this.UnitsForArmies = new HashSet<UnitsForArmies>();
        }
    
        public int Id { get; set; }
        public string UnitName { get; set; }
        public int UnitStrength { get; set; }
        public int UnitResistence { get; set; }
        public int UnitAttacks { get; set; }
        public string UnitRace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitsForArmies> UnitsForArmies { get; set; }
    }
}
