// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiNet6.Models;

public partial class Itworkers
{
    public int IdWorker { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public int? IdTask { get; set; }

    public virtual Tasks Tasks { get; set; }
}