// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiNet6.Models;

public partial class Tasks
{
    public int IdTask { get; set; }

    public string TaskName { get; set; }

    public string TaskDescription { get; set; }

    public int IdWorker { get; set; }

    public virtual Itworkers IdWorkerNavigation { get; set; }
}