// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleLoginRepository.Models
{
    public partial class UserPassword
    {
        public int UserId { get; set; }
        public string UserHash { get; set; }
        public string UserSalt { get; set; }

        public virtual Users User { get; set; }
    }
}