//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string AccountPin { get; set; }
        public decimal Money { get; set; }
        public Nullable<int> MovementId { get; set; }
    
        public virtual Movements Movements { get; set; }
    }
}
